os: Visual Studio 2015

platform:
  - x64

install:
  # Use the x86 python only when building for x86 for the cpython tests.
  # For all other archs (including, say, arm), use the x64 python.
  - cmd: set "MESON_FIXED_NINJA=1"
  - ps: (new-object net.webclient).DownloadFile('http://nirbheek.in/files/binaries/ninja/win32/ninja.exe', 'C:\projects\fanfaresimulator\ninja.exe')
  - cmd: if %arch%==x86 (set MESON_PYTHON_PATH=C:\python34) else (set MESON_PYTHON_PATH=C:\python34-x64)
  - cmd: echo Using Python at %MESON_PYTHON_PATH%
  - cmd: '%MESON_PYTHON_PATH%\Scripts\pip install meson'
  - cmd: if %compiler%==msvc2010 ( call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat" %arch% )
  - cmd: if %compiler%==msvc2015 ( call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %arch% )

build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake ..
  - cmd: msbuild fanfaresimulator.sln
