os: Visual Studio 2015

platform:
  - x64

build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -G "Visual Studio 14 2015 Win64" "-DCMAKE_PREFIX_PATH=C:\Qt\5.9.2\msvc2015_64" ..
  - cmd: msbuild fanfaresimulator.sln
