os: Visual Studio 2015

platform:
  - x64

before_build:
  - ps: (new-object net.webclient).DownloadFile('https://github.com/fanfaresimulator/fanfaresimulator/files/1505797/vendor.zip', 'C:\vendor.zip')
  - cmd: mkdir vendor
  - cmd: 7z x C:\vendor.zip -ovendor

build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -G "Visual Studio 14 2015 Win64" "-DCMAKE_PREFIX_PATH=C:\Qt\5.9.2\msvc2015_64" ..
  - cmd: msbuild fanfaresimulator.sln
