sudo: false
language: cpp
group: beta

os:
  - linux

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - python3
      - python3-pip

install:
  - export PATH="`pwd`/build:${PATH}"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install python3 ninja; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip && unzip -q ninja-linux.zip -d build; fi
  - pip3 install --user meson

script:
  - meson builddir
  - ninja -C builddir
  - ninja -C builddir test
