sudo: false
language: cpp
group: beta

os:
  - linux

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - boost-latest
    packages:
      - libboost-all-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
